name: ImageMap
version: 1.0
author: ShortCircuit908
website: http://dev.bukkit.org/bukkit-plugins/ImageMap/
main: com.shortcircuit.imagemap.ImageMap
commands:
  image:
    description: Render an image to a map
    usage: /<command> [URL]
  image:
    description: Delete unused images from the images folder
    usage: /<command> clean
  image:
    description: Remove an image from a map
    usage: /<command> remove
  