name: PicturePerfect
version: 1.1
author: ShortCircuit908
website: http://dev.bukkit.org/bukkit-plugins/PicturePerfect/
main: com.shortcircuit.pictureperfect.PicturePerfect
commands:
  image:
    description: Base command
    usage: /<command> [clean|list|remove|URL|file_name]
  